"use client";

import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { ErrorState } from "@/components/ui/error-state";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { StatusBadge } from "@/components/ui/status-badge";
import { getStaffError } from "@/features/staff/staff-error";
import type { StaffBooking, StaffCinema, StaffShowtime, StaffShowtimeSeat } from "@/features/staff/types";
import { getStaffBooking, getStaffBookings, getStaffCinema, getStaffShowtime, getStaffShowtimeSeats, getStaffShowtimes } from "@/lib/api/staff";
import type { PaginatedResponse } from "@/lib/api/types";
import { formatMMK } from "@/lib/formatters/currency";
import { formatMyanmarDateTime } from "@/lib/formatters/date-time";

const PAGE_SIZE = 20;
const showtimeStatuses = ["ACTIVE", "CANCELLED", "COMPLETED"] as const;
const bookingStatuses = ["PENDING", "CONFIRMED", "CANCELLED", "EXPIRED", "USED"] as const;

function Header({ title, description, back }: { title: string; description: string; back?: { href: string; label: string } }) {
  return <header className="border-b border-[var(--qs-border)] pb-5">{back ? <Link className="text-sm text-[var(--qs-text-muted)] hover:text-[var(--qs-text)]" href={back.href}>← {back.label}</Link> : null}<h1 className="mt-3 text-2xl font-semibold tracking-tight sm:text-3xl">{title}</h1><p className="mt-2 max-w-3xl text-sm text-[var(--qs-text-muted)] sm:text-base">{description}</p></header>;
}

function parseId(value: string | null): number | undefined { const id = Number(value); return Number.isSafeInteger(id) && id > 0 ? id : undefined; }
function parseDate(value: string | null): string { return value && /^\d{4}-\d{2}-\d{2}$/.test(value) ? value : ""; }
function parsePage(value: string | null): number { const page = Number.parseInt(value ?? "0", 10); return Number.isFinite(page) && page >= 0 ? page : 0; }
function listHref(pathname: string, params: URLSearchParams) { const query = params.toString(); return `${pathname}${query ? `?${query}` : ""}`; }

const primaryLinkClass = "inline-flex min-h-11 items-center justify-center rounded-lg border border-[var(--qs-primary)] bg-[var(--qs-primary)] px-4 py-2 text-sm font-semibold text-white transition-colors hover:border-[var(--qs-primary-strong)] hover:bg-[var(--qs-primary-strong)]";
const secondaryLinkClass = "inline-flex min-h-11 items-center justify-center rounded-lg border border-[var(--qs-border)] bg-[var(--qs-surface-raised)] px-4 py-2 text-sm font-semibold transition-colors hover:border-[#565661] hover:bg-[#2a2a31]";
const actionLinkClass = "inline-flex min-h-10 items-center justify-center rounded-lg border border-transparent px-3 py-2 text-sm font-semibold text-[var(--qs-text-muted)] hover:bg-white/5 hover:text-[var(--qs-text)]";

export function StaffWorkspacePage() {
  const [cinema, setCinema] = useState<StaffCinema | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setCinema((await getStaffCinema()).data); } catch (failure) { setError(getStaffError(failure).message); } finally { setLoading(false); } }, []);
  useEffect(() => { const request = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(request); }, [load]);
  return <div className="space-y-6"><Header title="Staff workspace" description="Read-only operations for your assigned QuickSeat cinema." />{loading ? <Card className="space-y-4"><Skeleton className="h-6 w-52" /><Skeleton className="h-4 w-80 max-w-full" /><Skeleton className="h-10 w-48" /></Card> : error ? <ErrorState action={<Button onClick={() => void load()} variant="secondary">Try again</Button>} description={error} title="Unable to load assigned cinema" /> : cinema ? <Card className="max-w-3xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-[var(--qs-text-muted)]">Assigned cinema</p><h2 className="mt-2 text-xl font-semibold">{cinema.name}</h2><p className="mt-2 text-sm text-[var(--qs-text-muted)]">{[cinema.city, cinema.address].filter(Boolean).join(" · ") || "Address was not included in the response."}</p></div><StatusBadge status={cinema.active ? "ACTIVE" : "INACTIVE"} /></div><div className="mt-6 flex flex-wrap gap-3"><Link className={primaryLinkClass} href="/staff/showtimes">View showtimes</Link><Link className={secondaryLinkClass} href="/staff/bookings">View bookings</Link></div></Card> : null}</div>;
}

export function StaffShowtimesPage() {
  const pathname = usePathname(); const router = useRouter(); const searchParams = useSearchParams(); const movieId = parseId(searchParams.get("movieId")); const date = parseDate(searchParams.get("date")); const rawStatus = searchParams.get("status") ?? ""; const status = showtimeStatuses.includes(rawStatus as (typeof showtimeStatuses)[number]) ? rawStatus : ""; const page = parsePage(searchParams.get("page"));
  const [result, setResult] = useState<PaginatedResponse<StaffShowtime> | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setResult((await getStaffShowtimes({ movieId, date: date || undefined, status: status as "ACTIVE" | "CANCELLED" | "COMPLETED" | undefined, page, size: PAGE_SIZE })).data); } catch (failure) { setError(getStaffError(failure).message); } finally { setLoading(false); } }, [date, movieId, page, status]);
  useEffect(() => { const request = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(request); }, [load]);
  function update(next: Record<string, string | number | undefined>) { const params = new URLSearchParams(searchParams.toString()); for (const [key, value] of Object.entries(next)) { if (value === undefined || value === "" || value === 0) params.delete(key); else params.set(key, String(value)); } router.push(listHref(pathname, params)); }
  return <div className="space-y-6"><Header title="Showtimes" description="Read-only showtimes for your assigned cinema." /><Card><form className="grid gap-3 md:grid-cols-4 md:items-end" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); update({ movieId: String(form.get("movieId") ?? ""), date: String(form.get("date") ?? ""), status: String(form.get("status") ?? ""), page: 0 }); }}><Field label="Movie ID"><Input defaultValue={movieId ? String(movieId) : ""} min="1" name="movieId" type="number" /></Field><Field label="Date"><Input defaultValue={date} name="date" type="date" /></Field><Field label="Status"><Select defaultValue={status} name="status"><option value="">All statuses</option>{showtimeStatuses.map((value) => <option key={value}>{value}</option>)}</Select></Field><Button type="submit" variant="secondary">Apply filters</Button></form></Card><ListState loading={loading} error={error} retry={load} empty={!result || result.content.length === 0} emptyTitle="No showtimes found">{result ? <><Card className="overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full min-w-[54rem] text-left text-sm"><thead className="bg-[#1d1d22] text-xs uppercase tracking-wider text-[var(--qs-text-muted)]"><tr><th className="px-4 py-3">Movie</th><th className="px-4 py-3">Screen</th><th className="px-4 py-3">Starts</th><th className="px-4 py-3">Prices</th><th className="px-4 py-3">Status</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-[var(--qs-border)]">{result.content.map((showtime) => <tr className="hover:bg-white/[0.02]" key={showtime.id}><td className="px-4 py-4 font-medium">{showtime.movieTitle ?? `Showtime ${showtime.id}`}</td><td className="px-4 py-4">{showtime.screenName ?? "—"}</td><td className="px-4 py-4">{showtime.startTime ? formatMyanmarDateTime(showtime.startTime) : "—"}</td><td className="px-4 py-4 text-xs">{showtime.normalPrice != null ? <p>Normal: {formatMMK(showtime.normalPrice)}</p> : null}{showtime.couplePrice != null ? <p>Couple: {formatMMK(showtime.couplePrice)}</p> : null}</td><td className="px-4 py-4"><StatusBadge status={showtime.status} /></td><td className="px-4 py-4 text-right"><Link className={actionLinkClass} href={`/staff/showtimes/${showtime.id}`}>View</Link></td></tr>)}</tbody></table></div></Card><Pagination page={result.page} total={result.totalElements} pages={result.totalPages} onChange={(nextPage) => update({ page: nextPage })} /></> : null}</ListState></div>;
}

export function StaffShowtimeDetailPage({ showtimeId }: { showtimeId: number }) {
  const [showtime, setShowtime] = useState<StaffShowtime | null>(null); const [seats, setSeats] = useState<StaffShowtimeSeat[] | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [detail, inventory] = await Promise.all([getStaffShowtime(showtimeId), getStaffShowtimeSeats(showtimeId)]); setShowtime(detail.data); setSeats(inventory.data.seats); } catch (failure) { setError(getStaffError(failure).message); } finally { setLoading(false); } }, [showtimeId]);
  useEffect(() => { const request = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(request); }, [load]);
  return <div className="space-y-6"><Header back={{ href: "/staff/showtimes", label: "Showtimes" }} title="Showtime detail" description="Backend-reported showtime and seat inventory for your assigned cinema." /><ListState loading={loading} error={error} retry={load} empty={!showtime} emptyTitle="Showtime not found">{showtime ? <><Card><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">{showtime.movieTitle ?? `Showtime ${showtime.id}`}</h2><p className="mt-1 text-sm text-[var(--qs-text-muted)]">{showtime.screenName ?? "Screen not included"}</p></div><StatusBadge status={showtime.status} /></div><dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><Detail label="Starts (Myanmar time)" value={showtime.startTime ? formatMyanmarDateTime(showtime.startTime) : "—"} /><Detail label="Ends (Myanmar time)" value={showtime.endTime ? formatMyanmarDateTime(showtime.endTime) : "—"} /><Detail label="Normal price" value={showtime.normalPrice != null ? formatMMK(showtime.normalPrice) : "—"} /><Detail label="Couple price" value={showtime.couplePrice != null ? formatMMK(showtime.couplePrice) : "—"} /></dl></Card><Card><h2 className="text-lg font-semibold">Seat inventory</h2>{seats && seats.length > 0 ? <div className="mt-5 overflow-x-auto"><div className="flex min-w-max flex-wrap gap-2">{seats.map((seat, index) => <div className="min-w-24 rounded-lg border border-[var(--qs-border)] bg-[var(--qs-surface-raised)] p-3 text-sm" key={seat.showtimeSeatId ?? index}><p className="font-semibold">{seat.rowName ?? ""}{seat.seatNumber ?? "Seat"}</p><p className="mt-1 text-xs text-[var(--qs-text-muted)]">{seat.seatType ?? "Seat"}{seat.price != null ? ` · ${formatMMK(seat.price)}` : ""}</p><div className="mt-2"><StatusBadge status={seat.status} /></div></div>)}</div></div> : <p className="mt-3 text-sm text-[var(--qs-text-muted)]">No seat inventory was returned for this showtime.</p>}</Card></> : null}</ListState></div>;
}

export function StaffBookingsPage() {
  const pathname = usePathname(); const router = useRouter(); const searchParams = useSearchParams(); const search = searchParams.get("search")?.trim() ?? ""; const date = parseDate(searchParams.get("date")); const showtimeId = parseId(searchParams.get("showtimeId")); const rawStatus = searchParams.get("status") ?? ""; const status = bookingStatuses.includes(rawStatus as (typeof bookingStatuses)[number]) ? rawStatus : ""; const page = parsePage(searchParams.get("page"));
  const [result, setResult] = useState<PaginatedResponse<StaffBooking> | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setResult((await getStaffBookings({ search: search || undefined, date: date || undefined, showtimeId, status: status || undefined, page, size: PAGE_SIZE })).data); } catch (failure) { setError(getStaffError(failure).message); } finally { setLoading(false); } }, [date, page, search, showtimeId, status]);
  useEffect(() => { const request = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(request); }, [load]);
  function update(next: Record<string, string | number | undefined>) { const params = new URLSearchParams(searchParams.toString()); for (const [key, value] of Object.entries(next)) { if (value === undefined || value === "" || value === 0) params.delete(key); else params.set(key, String(value)); } router.push(listHref(pathname, params)); }
  return <div className="space-y-6"><Header title="Bookings" description="Read-only booking records for your assigned cinema." /><Card><form className="grid gap-3 md:grid-cols-2 xl:grid-cols-5 xl:items-end" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); update({ search: String(form.get("search") ?? "").trim(), status: String(form.get("status") ?? ""), showtimeId: String(form.get("showtimeId") ?? ""), date: String(form.get("date") ?? ""), page: 0 }); }}><Field label="Search"><Input defaultValue={search} name="search" placeholder="Booking reference" /></Field><Field label="Status"><Select defaultValue={status} name="status"><option value="">All statuses</option>{bookingStatuses.map((value) => <option key={value}>{value}</option>)}</Select></Field><Field label="Showtime ID"><Input defaultValue={showtimeId ? String(showtimeId) : ""} min="1" name="showtimeId" type="number" /></Field><Field label="Date"><Input defaultValue={date} name="date" type="date" /></Field><Button type="submit" variant="secondary">Apply filters</Button></form></Card><ListState loading={loading} error={error} retry={load} empty={!result || result.content.length === 0} emptyTitle="No bookings found">{result ? <><Card className="overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full min-w-[60rem] text-left text-sm"><thead className="bg-[#1d1d22] text-xs uppercase tracking-wider text-[var(--qs-text-muted)]"><tr><th className="px-4 py-3">Booking</th><th className="px-4 py-3">Movie / Screen</th><th className="px-4 py-3">Showtime</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Status</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-[var(--qs-border)]">{result.content.map((booking) => <tr className="hover:bg-white/[0.02]" key={booking.bookingReference}><td className="px-4 py-4 font-mono font-semibold">{booking.bookingReference}</td><td className="px-4 py-4"><p>{booking.movieTitle ?? "—"}</p><p className="mt-1 text-xs text-[var(--qs-text-muted)]">{booking.screenName ?? ""}</p></td><td className="px-4 py-4">{booking.startTime ? formatMyanmarDateTime(booking.startTime) : "—"}</td><td className="px-4 py-4 font-semibold">{booking.totalAmount != null ? formatMMK(booking.totalAmount) : "—"}</td><td className="px-4 py-4"><StatusBadge status={booking.status} /></td><td className="px-4 py-4 text-right"><Link className={actionLinkClass} href={`/staff/bookings/${encodeURIComponent(booking.bookingReference)}`}>View</Link></td></tr>)}</tbody></table></div></Card><Pagination page={result.page} total={result.totalElements} pages={result.totalPages} onChange={(nextPage) => update({ page: nextPage })} /></> : null}</ListState></div>;
}

export function StaffBookingDetailPage({ bookingReference }: { bookingReference: string }) {
  const [booking, setBooking] = useState<StaffBooking | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setBooking((await getStaffBooking(bookingReference)).data); } catch (failure) { setError(getStaffError(failure).message); } finally { setLoading(false); } }, [bookingReference]);
  useEffect(() => { const request = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(request); }, [load]);
  return <div className="space-y-6"><Header back={{ href: "/staff/bookings", label: "Bookings" }} title="Booking detail" description="Backend-reported booking context for your assigned cinema." /><ListState loading={loading} error={error} retry={load} empty={!booking} emptyTitle="Booking not found">{booking ? <Card><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-[var(--qs-text-muted)]">Booking reference</p><p className="mt-1 break-all font-mono text-xl font-bold">{booking.bookingReference}</p></div><StatusBadge status={booking.status} /></div><dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-3"><Detail label="Customer" value={booking.customerName ?? "—"} /><Detail label="Customer email" value={booking.customerEmail ?? "—"} /><Detail label="Movie" value={booking.movieTitle ?? "—"} /><Detail label="Cinema" value={booking.cinemaName ?? "—"} /><Detail label="Screen" value={booking.screenName ?? "—"} /><Detail label="Showtime (Myanmar time)" value={booking.startTime ? formatMyanmarDateTime(booking.startTime) : "—"} /><Detail label="Total amount" value={booking.totalAmount != null ? formatMMK(booking.totalAmount) : "—"} /><Detail label="Payment status" value={booking.paymentStatus ?? "—"} /><Detail label="Ticket status" value={booking.ticketStatus ?? "—"} /></dl><SeatList seats={booking.seats ?? []} /></Card> : null}</ListState></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium">{label}{children}</label>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-semibold uppercase tracking-wider text-[var(--qs-text-muted)]">{label}</dt><dd className="mt-1 break-words font-medium">{value}</dd></div>; }
function SeatList({ seats }: { seats: unknown[] }) { return <section className="mt-7 border-t border-[var(--qs-border)] pt-5"><h2 className="text-lg font-semibold">Seats</h2>{seats.length ? <ul className="mt-3 flex flex-wrap gap-2">{seats.map((seat, index) => <li className="rounded-lg border border-[var(--qs-border)] px-3 py-2 text-sm" key={index}>{seatLabel(seat)}</li>)}</ul> : <p className="mt-2 text-sm text-[var(--qs-text-muted)]">Seat details were not included in this response.</p>}</section>; }
function seatLabel(value: unknown) { if (!value || typeof value !== "object") return String(value ?? "Seat"); const seat = value as Record<string, unknown>; const row = typeof seat.rowName === "string" ? seat.rowName : ""; const number = typeof seat.seatNumber === "number" || typeof seat.seatNumber === "string" ? String(seat.seatNumber) : ""; return row || number ? `${row}${number}` : "Seat"; }
function Pagination({ page, pages, total, onChange }: { page: number; pages: number; total: number; onChange: (page: number) => void }) { return <div className="flex flex-wrap items-center justify-between gap-3 border-t border-[var(--qs-border)] pt-4"><p className="text-sm text-[var(--qs-text-muted)]">{total} records · Page {pages ? page + 1 : 0} of {pages}</p><div className="flex gap-2"><Button disabled={page <= 0} onClick={() => onChange(page - 1)} variant="secondary">Previous</Button><Button disabled={pages === 0 || page >= pages - 1} onClick={() => onChange(page + 1)} variant="secondary">Next</Button></div></div>; }
function ListState({ loading, error, retry, empty, emptyTitle, children }: { loading: boolean; error: string; retry: () => Promise<void>; empty: boolean; emptyTitle: string; children: React.ReactNode }) { if (loading) return <Card className="space-y-3" role="status">{Array.from({ length: 5 }, (_, index) => <Skeleton className="h-16" key={index} />)}</Card>; if (error) return <ErrorState action={<Button onClick={() => void retry()} variant="secondary">Try again</Button>} description={error} title="Unable to load staff data" />; if (empty) return <EmptyState description="The backend did not return a matching record." title={emptyTitle} />; return <>{children}</>; }
